#pragma once
#include<memory>
template <class T1,class T2>
constexpr inline auto Max(T1 a, T2 b) {
	return a>b?a:b;
}

template <class T1, class T2,class ...TN>
constexpr inline auto Max(T1 a, T2 b, TN... args) {
	return Max(Max(a, b), args...);
}

template<typename T1,typename T2>
constexpr inline auto Min(T1 a, T2 b) {
	return a<b?a:b;
}

template<typename T1, typename T2, typename ...TN>
constexpr inline auto Min(T1 a, T2 b, TN... args) {
	return Min(Min(a, b), args...);
}

#ifndef ADTCLASSBEGIN 
#define ADTFUNCBEGIN			template<typename ElemType>
#define ADTCLASSBEGIN(ADTNAME)	ADTFUNCBEGIN struct ADTNAME

#define ADTCLASSEND ;
#define ADTFUNCEND ADTCLASSEND
#endif

#ifndef ADTCALLFUNCBEGIN
#define ADTCALLFUNCBEGIN template<typename ElemType,typename Callable>
#define ADTCALLFUNCEND
#endif

#ifndef ADTSORTBEGIN
#define ADTSORTBEGIN	template<typename ElemType,typename Predicate=std::less<ElemType>>
#define ADTSORTEND
#define PREDTYPE		Predicate
#endif

#ifndef ADTBEGIN
#define ADTBEGIN				namespace ADT{
#define ADTSUBBEGIN(ADTNAME)	namespace ADT##ADTNAME{
#endif

#ifndef ADTEND
#define ADTEND };
#define ADTSUBEND ADTEND
#endif // !ADTEND

#ifndef ADTMAXSIZE
#define ADTMAXSIZE 10
#endif // !ADTMAXSIZE

#ifndef ADTTYPE
#define ADTTYPE(ADTNAME)		ADTNAME<ElemType>
#define ADTREFER(ADTNAME)		ADTTYPE(ADTNAME)&
#define ADTCONSTREFER(ADTNAME)	const ADTREFER(ADTNAME)
#define ADTPOINTER(ADTNAME)		ADTTYPE(ADTNAME)*
#define ADTCONSTPOINTER(ADTNAME)	const ADTPOINTER(ADTNAME)
#define ADTWARPPERPOINTER(ADTNAME)	std::unique_ptr<ADTTYPE(ADTNAME)>
#endif // !ADTTYPE

#ifndef ARGTYPE
#define ARGTYPE				ElemType
#define ARGREFER			ARGTYPE&
#define ARGCONSTREFER		const ARGREFER
#define ARGPOINTER			ARGTYPE*
#define ARGWARPPERPOINTER	std::unique_ptr<ARGTYPE>
#endif

#ifndef FUNCTYPE
#define FUNCTYPE Callable
#define SORTFUNC Predicate
#endif // !FUNCTYPE


#ifndef ADTATTRIURBUTE
#define ADTIN(ADTNAME)	ADTCONSTREFER(ADTNAME)
#define ADTOUT(ADTNAME)	ADTTYPE(ADTNAME)
#define ADTINOUT(ADTNAME) ADTREFER(ADTNAME)
#endif // !ADTATTRIURBUTE

#ifndef ARGATTRIUBUTE
#define ARGIN ARGCONSTREFER
#define ARGOUT ARGREFER
#define ARGINOUT ARGREFER
#endif // !ARGATTRIBUTE

#ifndef ADTARRAYTYPE
#define ADTARRATTYPE std::unique_ptr<ARGTYPE[]> 
#define ADTVECTORTYPE ARGWARPPERPOINTER
#endif

#ifndef ASSIGNFUNC
#define ASSIGNFUNC(FUNCNAME,ADTNAME,TYPE) TYPE FUNCNAME##ADTNAME
#define ASSIGNINITADT(ADTNAME)	ASSIGNFUNC(Init,ADTNAME,void)
#define ASSIGNDESTORYADT(ADTNAME)  ASSIGNFUNC(Destroy,ADTNAME,void)
#define ASSIGNCLEARADT(ADTNAME)	ASSIGNFUNC(Clear,ADTNAME,void)
#define ASSIGNEMPTYADT(ADTNAME) ASSIGNFUNC(ADTNAME,Empty,bool)
#define ASSIGNLENGTHADT(ADTNAME) ASSIGNFUNC(ADTNAME,Length,size_t)
#define ASSIGNTRANVERSEADT(ADTNAME) ASSIGNFUNC(Tranverse,ADTNAME,void)
#endif // !ASSIGNFUNC

#define ARGLIST		/*ARGLIST*/
#define ASSIGNINIT(ADTNAME,ARGNAME) ASSIGNINITADT(ADTNAME)(ADTINOUT(ADTNAME)ARGNAME)
#define ASSIGNDESTORY(ADTNAME,/*ARGLIST*/ARGNAME) ASSIGNDESTORYADT(ADTNAME)(ADTINOUT(ADTNAME)ARGNAME)
#define ASSIGNCLEAR(ADTNAME,/*ARGLIST*/ARGNAME) ASSIGNCLEARADT(ADTNAME)(ADTINOUT(ADTNAME)ARGNAME)
#define ASSIGNEMPTY(ADTNAME,/*ARGLIST*/ARGNAME) ASSIGNEMPTYADT(ADTNAME)(ADTIN(ADTNAME)ARGNAME)
#define ASSIGNLENGTH(ADTNAME,/*ARGLIST*/ARGNAME) ASSIGNLENGTHADT(ADTNAME)(ADTIN(ADTNAME)ARGNAME)
#define ASSIGNTRANVERSE(ADTNAME,/*ARGLIST*/ARG1,ARG2) ASSIGNTRANVERSEADT(ADTNAME)(ADTINOUT(ADTNAME)ARG1,FUNCTYPE ARG2)
#define ASSIGNELEMFUNC(OP,TYPE) TYPE OP##Elem 

#ifdef LIST

#define ASSIGNGETELEM(ADTNAME,/*ARGLIST*/ARG1,POS,ARG2) ASSIGNELEMFUNC(Get,bool)(ADTIN(ADTNAME)ARG1,size_t POS,ARGOUT ARG2)
#define ASSIGNLOCATE(ADTNAME,/*ARGLIST*/ARG1,ARG2)ASSIGNELEMFUNC(Locate,size_t)(ADTIN(ADTNAME) ARG1,ARGIN ARG2)
#define ASSIGNPRIORELEM(ADTNAME,/*ARGLIST*/ARG1,ARG2,ARG3) ASSIGNELEMFUNC(Prior,bool)(ADTIN(ADTNAME)ARG1,ARGIN ARG2,ARGOUT ARG3)
#define ASSIGNNEXTELEM(ADTNAME,/*ARGLIST*/ARG1,ARG2,ARG3) ASSIGNELEMFUNC(Next,bool)(ADTIN(ADTNAME)ARG1,ARGIN ARG2,ARGOUT ARG3)

#define	ASSIGNINSERT(ADTNAME,/*ARGLIST*/ARG1,POS,ARG2) ASSIGNFUNC(ADTNAME,Insert,bool)(ADTINOUT(ADTNAME)ARG1,size_t POS,ARGIN ARG2)
#define ASSIGNDELETE(ADTNAME,/*ARGLIST*/ARG1,POS) ASSIGNFUNC(ADTNAME,Delete,bool)(ADTINOUT(ADTNAME)ARG1,size_t POS)

#endif

#ifdef QUEUE
#define ASSIGNENQUEUE(ADTNAME,ARG1,ARG2) ASSIGNFUNC(En,Queue,bool)(ADTINOUT(ADTNAME)ARG1,ARGIN ARG2)
#define ASSIGNDEQUEUE(ADTNAME,ARG1,ARG2) ASSIGNFUNC(De,Queue,bool)(ADTINOUT(ADTNAME)ARG1,ARGOUT ARG2)
#endif // QUEUE

#ifdef STACK
#define ASSIGNPUSH(ADTNAME,ARG1,ARG2) ASSIGNFUNC(Push,Stack,bool)(ADTINOUT(ADTNAME)ARG1,ARGIN ARG2)
#define ASSIGNPOP(ADTNAME,ARG1,ARG2) ASSIGNFUNC(Pop,Stack,bool) (ADTINOUT(ADTNAME)ARG1,ARGOUT ARG2)
#define ASSIGNTOP(ADTNAME,ARG1)	  ASSIGNFUNC(Get,Top,ARGTYPE)(ADTIN(ADTNAME)ARG1)
#endif // STACK

